# You need to pass $_TNL_VERSION value (usually it will be $TAG_NAME)
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-f', 'docker/Dockerfile',
            '--build-arg', 'TNL_VERSION=${_TNL_VERSION}',
            '-t', 'gcr.io/$PROJECT_ID/tcpnetlock:${_TNL_VERSION}',
            '-t', 'gcr.io/$PROJECT_ID/tcpnetlock:latest',
            '.'
        ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/tcpnetlock']
images:
- 'gcr.io/$PROJECT_ID/tcpnetlock:${_TNL_VERSION}'
- 'gcr.io/$PROJECT_ID/tcpnetlock:latest'
